version: '2'
services:
  devops_pipeline_demo-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/devops_pipeline_demo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=devops_pipeline_demo
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
